
[cursor]
style = "Beam"

[font]
size = 14.0

[general]
import = [
  "~/.config/alacritty/nord.toml", # colors
# "~/.config/alacritty/nord.toml",
# "~/.config/alacritty/nord_light.toml",
# "~/.config/alacritty/seoul256_dark.toml",
# "~/.config/alacritty/solarized_light.toml",
# "~/.config/alacritty/solarized_dark.toml",
]
